# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
    - uses: actions/cache@v3
      name: Turbo Cache
      with:
        key: turbo-cache-8ce4a94f-0de9-465b-a035-a96fb0add57d
        path: |
          node_modules/.cache/turbo
    - if: ${{ steps.turbo-cache-8ce4a94f-0de9-465b-a035-a96fb0add57d.outputs.cache-hit == 'true' }}
      name: List the contents of turbo cache
      continue-on-error: true
      run: ls node_modules/.cache/turbo
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
